name: Build iOS App

on:
  push:
    tags:
      - 'ios@*'

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Xcode
        run: sudo xcode-select -s /Applications/Xcode.app

      - name: Install dependencies
        run: |
          # If you're using CocoaPods
          pod install --project-directory=./YourProjectDirectory

      - name: Build the app
        run: |
          xcodebuild build \
            -workspace ./ios/Memo.xcworkspace \ # Use .xcodeproj if not using CocoaPods
            -scheme Memo \
            -sdk iphonesimulator \
            -configuration Release \
            CODE_SIGN_IDENTITY="" \
            CODE_SIGNING_REQUIRED=NO \
            CODE_SIGNING_ALLOWED=NO

      - name: Archive build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: BuildProducts
          path: |
            ./ios/build
            # Add other paths if needed
